---
id: fukuokarb-200-lt
base_name: ruby-3.0
tags:
- ruby
presentation_date: '2021-03-24'
presentation_start_time:
presentation_end_time:
version: 2021.3.24.0
licenses: []
slideshare_id:
speaker_deck_id:
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
